# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smocky < Formula
  desc "Smocky is a mocking tool"
  homepage "https://github.com/tuongaz/smocky"
  version "0.0.62"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.62/smocky_v0.0.62_darwin_arm64.tar.gz"
      sha256 "5a945a24df8439652b2f6ea6efa44c10abe9d43c8b7b2fb4da13bb10726e29c2"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.62/smocky_v0.0.62_darwin_amd64.tar.gz"
      sha256 "7d7614a067348a9849270b5d2d9621633715baced23890e0a8632d5503dfb700"

      def install
        bin.install "smocky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.62/smocky_v0.0.62_linux_arm64.tar.gz"
      sha256 "2f42365b8515f5e9413cd9bc79389d6ee184ec45288319fa99cde664062c30da"

      def install
        bin.install "smocky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tuongaz/smocky/releases/download/v0.0.62/smocky_v0.0.62_linux_amd64.tar.gz"
      sha256 "3f8621d493204a0279954855b7b08f29924249a083ff3bbdfc0b2bb8950b3301"

      def install
        bin.install "smocky"
      end
    end
  end

  test do
    system "#{bin}/smocky --version"
  end
end
